### ISSUE TITLE
Chào

### ISSUE THREAD

**Issue by daominh89** [tran1903alt/tran1903alt.github.io#1]
Dạo này thấy bạn ko online trên discord nữa nhỉ

Mà nhóm coder gang bốc hơi đi đầu rồi???

**Comment by beobuild** [comment]
bạn là ai nhỉ?

**Comment by daominh89** [comment]
> bạn là ai nhỉ?

bạn quên mình rồi hả, sao nhanh vậy??

**Comment by daominh89** [comment]
bạn nhớ hiếu python ko
